### ISSUE TITLE
Cannot buy ad - paypal box crashes

### ISSUE THREAD

**Issue by 153** [mixflame/Gbaldraw2#2]
https://gbaldraw.fun/buy_ad

I've uploaded my ad image and link to the url ( ` //0chan.vip` ) in the box -- when clicking the Paypal buttons, the paypal dialog instantly crashes and I cannot proceed.  I would like to buy an ad. As a workaround, maybe you could give me your paypal address here, or send it to me on Rizon? My Rizon nick is ` casio `. 

[![](https://i.imgur.com/GdelBFx.png)](//0chan.vip)

**Comment by 153** [comment]
I am imagining this Gbaldraw2 project is associated with https://gbaldraw.fun/ -- please disregard this issue if not. Thanks!

**Comment by mixflame** [comment]
Hey `casio` this is a different version of Gbaldraw than what's on the site but it's fine to post issues here since the site's code is private right now.

I will look into the broken paypal ad upload and leave an update here.

**Comment by mixflame** [comment]
Hey `casio` looks like this issue has been resolved. Please attempt to use the banner ad uploader again. It was an issue having to do with a feature being removed when I upgraded the site. I have patched it back it.
